# Generated by Django 5.0.1 on 2024-01-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='навзвание')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='изображение')),
                ('price_for_1', models.IntegerField(verbose_name='цена за штуку')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_last_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('price_for_1',),
            },
        ),
    ]
